# Generated by Django 3.0 on 2023-04-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videomodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video')),
                ('content', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='images/logo')),
            ],
        ),
    ]
